added: support different major Elgg versions

diff --git a/.github/workflows/phpunit.yml b/.github/workflows/phpunit.yml
--- a/.github/workflows/phpunit.yml
+++ b/.github/workflows/phpunit.yml
@@ -2,6 +2,11 @@ name: PHPUnit Plugin Tests
 
 on:
   workflow_call:
+    inputs:
+      elgg_major_version:
+        description: 'Major Elgg version number'
+        default: 5
+        type: number
 
 env:
   ELGG_DB_PREFIX: c_i_elgg_
@@ -15,10 +20,12 @@ env:
   ELGG_MEMCACHE_NAMESPACE_PREFIX: elgg_
   ELGG_REDIS_SERVER1_HOST: 127.0.0.1
   ELGG_REDIS_SERVER1_PORT: 6379
+  ELGG_BRANCH: ${{ inputs.elgg_major_version == 5 && '5.1' || '6.x' }}
+  ELGG_PHP_VERSION: ${{ inputs.elgg_major_version == 5 && '8.0' || '8.1' }}
 
 jobs:
   phpunit:
-    name: Run PHPUnit test suites
+    name: Run PHPUnit test suites for Elgg ${{ inputs.elgg_major_version }}
     
     runs-on: ubuntu-latest
     
@@ -32,32 +39,35 @@ jobs:
           - 3306:3306
 
     steps:
-      - name: Install PHP
+      - name: Validate Elgg major version
+        run: if [[ ! "${{ inputs.elgg_major_version }}" =~ ^(5|6)$ ]]; then echo "Invalid major Elgg version. Choose 5 or 6"; exit 1; fi
+
+      - name: Install PHP v${{ env.ELGG_PHP_VERSION }}
         uses: shivammathur/setup-php@v2
         with:
-          php-version: '8.0'
+          php-version: ${{ env.ELGG_PHP_VERSION }}
           coverage: none
-          extensions: gd,pdo,xml,json,mysqli,pdo_mysql
+          extensions: gd,pdo,xml,json,mysqli,pdo_mysql,intl
 
       - name: Get Composer Cache Directory
         id: composer-cache
         run: echo "dir=$(composer config cache-files-dir)" >> ${GITHUB_OUTPUT}
 
       - name: Restore Composer Cache
-        uses: actions/cache@v3
+        uses: actions/cache@v4
         with:
           path: ${{ steps.composer-cache.outputs.dir }}
           key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
           restore-keys: ${{ runner.os }}-composer-
 
-      - name: Code checkout Elgg
-        uses: actions/checkout@v3
+      - name: Code checkout Elgg v${{ env.ELGG_BRANCH }}
+        uses: actions/checkout@v4
         with:
           repository: 'Elgg/Elgg'
-          ref: '5.x'
+          ref: ${{ env.ELGG_BRANCH }}
 
       - name: Code checkout plugin
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
         with:
           clean: false
           path: 'mod/${{ github.event.repository.name }}'
